name: diamond_time
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Namaz & Takvim
  adhan: ^2.0.0
  intl: ^0.20.2
  hijri: ^3.0.0
  hijri_date_time: ^1.1.0

  # ✅ Zaman & Saat Dilimi (Versiyonlar yükseltildi)
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1

  # Konum ve Harita (ÜCRETSİZ)
  geolocator: ^13.0.1
  geocoding: ^4.0.0
  flutter_compass: ^0.8.0
  flutter_map: ^8.2.0
  latlong2: ^0.9.1
  scrollable_positioned_list: ^0.3.8
  
  # Sistem
  shared_preferences: ^2.3.5
  http: ^1.3.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1

  # ✅ Bildirim (Zaman paketiyle uyumlu en son sürüm)
  flutter_local_notifications: ^19.5.0

  # Sosyal & Veritabanı
  share_plus: ^12.0.1
  sqflite: ^2.4.1
  path: ^1.9.1
  home_widget: ^0.8.1
  dio: ^5.9.0
  gal: ^2.3.2  # Modern ve hızlı galeri paketi


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ✅ İkon paketi güncel versiyon
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

# ✅ İkon Ayarları
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A0E1A"
  adaptive_icon_foreground: "assets/icon.png"

  #widget
  home_widget: ^0.7.1